LOAD 'pg_typescript';

CREATE EXTENSION IF NOT EXISTS pg_typescript;

CREATE OR REPLACE FUNCTION public.ts_generate_fun_payload()
RETURNS jsonb
LANGUAGE typescript
SET typescript.import_map = '{"imports":{"faker":"https://esm.sh/@faker-js/faker@9.9.0"}}'
AS $$
  const f = faker.faker;

  const title = `${f.word.adjective()} ${f.word.noun()}`;
  const vibe = f.helpers.arrayElement([
    "space disco",
    "underwater rave",
    "cabin synth",
    "desert neon",
    "cloud city",
  ]);
  const tags = f.helpers.arrayElements(
    ["postgres", "typescript", "postgrest", "json", "demo", "fun"],
    { min: 2, max: 4 },
  );

  return {
    title,
    vibe,
    color: f.color.human(),
    by: f.person.firstName(),
    quote: f.hacker.phrase(),
    tags,
    stats: {
      sparkle: f.number.int({ min: 1, max: 10 }),
      chaos: f.number.int({ min: 1, max: 10 }),
      luck: f.number.int({ min: 1, max: 99 }),
    },
  };
$$;

DROP TABLE IF EXISTS public.postgrest_notes;

CREATE TABLE public.postgrest_notes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  payload jsonb NOT NULL DEFAULT public.ts_generate_fun_payload(),
  created_at timestamptz NOT NULL DEFAULT now()
);

GRANT USAGE ON SCHEMA public TO web_anon;
GRANT SELECT, INSERT ON TABLE public.postgrest_notes TO web_anon;
GRANT USAGE, SELECT ON SEQUENCE public.postgrest_notes_id_seq TO web_anon;
GRANT EXECUTE ON FUNCTION public.ts_generate_fun_payload() TO web_anon;
