\timing on
\set ON_ERROR_STOP on

\echo '=== preload (shared library load) ==='
LOAD 'pg_typescript';

\echo '=== setup ==='
CREATE EXTENSION IF NOT EXISTS pg_typescript;
SET client_min_messages = warning;
SET typescript.max_allow_pg_execute = 'on';

-- Build a small but non-trivial local dataset:
-- 25 users, 20 memberships each, and 5 notes per project.
DROP TABLE IF EXISTS profile_project_notes;
DROP TABLE IF EXISTS profile_project_members;
DROP TABLE IF EXISTS profile_projects;

CREATE UNLOGGED TABLE profile_projects (
  id integer PRIMARY KEY,
  name text NOT NULL
);

CREATE UNLOGGED TABLE profile_project_members (
  user_id integer NOT NULL,
  project_id integer NOT NULL,
  role text NOT NULL,
  PRIMARY KEY (user_id, project_id)
);

CREATE UNLOGGED TABLE profile_project_notes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id integer NOT NULL,
  body text NOT NULL
);

INSERT INTO profile_projects (id, name)
SELECT id, format('Project %s', id)
FROM generate_series(1, 200) AS g(id);

INSERT INTO profile_project_members (user_id, project_id, role)
SELECT
  user_id,
  ((user_id - 1) * 4 + slot - 1) % 200 + 1 AS project_id,
  CASE slot % 3
    WHEN 1 THEN 'owner'
    WHEN 2 THEN 'editor'
    ELSE 'viewer'
  END AS role
FROM generate_series(1, 25) AS u(user_id)
CROSS JOIN generate_series(1, 20) AS s(slot);

INSERT INTO profile_project_notes (project_id, body)
SELECT
  p.id,
  format('note %s for project %s', note_idx, p.id)
FROM profile_projects AS p
CROSS JOIN generate_series(1, 5) AS g(note_idx);

-- TypeScript baseline: fetch memberships, fetch notes for those projects, then
-- assemble the final JSON shape in JS.
CREATE OR REPLACE FUNCTION ts_profile_project_digest(in_user_id integer) RETURNS jsonb
LANGUAGE typescript
SET typescript.allow_pg_execute = 'on'
AS $fn$
  type MembershipRow = {
    project_id: number;
    project_name: string;
    role: string;
  };

  type NoteRow = {
    project_id: number;
    body: string;
  };

  const memberships = _pg.execute<MembershipRow>(
    `
      SELECT
        pm.project_id,
        p.name AS project_name,
        pm.role
      FROM profile_project_members AS pm
      JOIN profile_projects AS p
        ON p.id = pm.project_id
      WHERE pm.user_id = $1
      ORDER BY pm.project_id
    `,
    in_user_id,
  ).rows;

  if (memberships.length === 0) {
    return [];
  }

  // Expand the project IDs into $1, $2, ... placeholders so the second query
  // still uses bound parameters rather than string-interpolated values.
  const projectIds = [...new Set(memberships.map((row) => row.project_id))];
  const placeholders = projectIds.map((_, index) => `$${index + 1}`).join(", ");

  const notes = _pg.execute<NoteRow>(
    `
      SELECT
        project_id,
        body
      FROM profile_project_notes
      WHERE project_id IN (${placeholders})
      ORDER BY project_id, id
    `,
    ...projectIds,
  ).rows;

  // Group the second query's rows once, then attach each note list to the
  // corresponding membership record.
  const notesByProject = new Map<number, string[]>();
  for (const note of notes) {
    const grouped = notesByProject.get(note.project_id) ?? [];
    grouped.push(note.body);
    notesByProject.set(note.project_id, grouped);
  }

  return memberships.map((membership) => ({
    projectId: membership.project_id,
    projectName: membership.project_name,
    role: membership.role,
    notes: notesByProject.get(membership.project_id) ?? [],
  }));
$fn$;

-- SQL baseline: produce the same JSON shape inside Postgres using JSONB
-- builders and aggregation.
CREATE OR REPLACE FUNCTION sql_profile_project_digest(in_user_id integer) RETURNS jsonb
LANGUAGE sql STABLE AS $$
  WITH memberships AS (
    SELECT
      pm.project_id,
      p.name AS project_name,
      pm.role
    FROM profile_project_members AS pm
    JOIN profile_projects AS p
      ON p.id = pm.project_id
    WHERE pm.user_id = in_user_id
  )
  SELECT COALESCE(
    jsonb_agg(
      jsonb_build_object(
        'projectId', m.project_id,
        'projectName', m.project_name,
        'role', m.role,
        'notes', COALESCE(n.notes, '[]'::jsonb)
      )
      ORDER BY m.project_id
    ),
    '[]'::jsonb
  )
  FROM memberships AS m
  LEFT JOIN LATERAL (
    SELECT jsonb_agg(pn.body ORDER BY pn.id) AS notes
    FROM profile_project_notes AS pn
    WHERE pn.project_id = m.project_id
  ) AS n ON true;
$$;

\echo '=== dataset ==='
SELECT
  (SELECT count(*) FROM profile_projects) AS projects,
  (SELECT count(*) FROM profile_project_members) AS memberships,
  (SELECT count(*) FROM profile_project_notes) AS notes,
  jsonb_array_length(ts_profile_project_digest(1)) AS projects_returned_for_user_1;

\echo '=== per-call timing (1 cold + 100 warm) ==='
DROP TABLE IF EXISTS pg_typescript_profile_samples;
CREATE UNLOGGED TABLE pg_typescript_profile_samples (
  engine text NOT NULL,
  iter integer NOT NULL,
  elapsed_us double precision NOT NULL,
  PRIMARY KEY (engine, iter)
);

DO $$
DECLARE
  i integer;
  user_id integer;
  t0 timestamptz;
  t1 timestamptz;
  outv jsonb;
BEGIN
  t0 := clock_timestamp();
  outv := ts_profile_project_digest(1);
  t1 := clock_timestamp();
  INSERT INTO pg_typescript_profile_samples(engine, iter, elapsed_us)
  VALUES ('typescript_pg_execute', 0, EXTRACT(epoch FROM (t1 - t0)) * 1000000.0);

  FOR i IN 1..100 LOOP
    -- Cycle through several users so the warm path is not measuring the exact
    -- same logical result on every iteration.
    user_id := ((i - 1) % 25) + 1;
    t0 := clock_timestamp();
    outv := ts_profile_project_digest(user_id);
    t1 := clock_timestamp();
    INSERT INTO pg_typescript_profile_samples(engine, iter, elapsed_us)
    VALUES ('typescript_pg_execute', i, EXTRACT(epoch FROM (t1 - t0)) * 1000000.0);
  END LOOP;
END;
$$;

DO $$
DECLARE
  i integer;
  user_id integer;
  t0 timestamptz;
  t1 timestamptz;
  outv jsonb;
BEGIN
  t0 := clock_timestamp();
  outv := sql_profile_project_digest(1);
  t1 := clock_timestamp();
  INSERT INTO pg_typescript_profile_samples(engine, iter, elapsed_us)
  VALUES ('sql_json', 0, EXTRACT(epoch FROM (t1 - t0)) * 1000000.0);

  FOR i IN 1..100 LOOP
    user_id := ((i - 1) % 25) + 1;
    t0 := clock_timestamp();
    outv := sql_profile_project_digest(user_id);
    t1 := clock_timestamp();
    INSERT INTO pg_typescript_profile_samples(engine, iter, elapsed_us)
    VALUES ('sql_json', i, EXTRACT(epoch FROM (t1 - t0)) * 1000000.0);
  END LOOP;
END;
$$;

\echo '=== summary (microseconds) ==='
SELECT
  engine,
  round((MAX(elapsed_us) FILTER (WHERE iter = 0))::numeric, 3) AS cold_first_call_us,
  round((AVG(elapsed_us) FILTER (WHERE iter > 0))::numeric, 3) AS warm_avg_us,
  round((percentile_cont(0.50) WITHIN GROUP (ORDER BY elapsed_us)
    FILTER (WHERE iter > 0))::numeric, 3) AS warm_p50_us,
  round((percentile_cont(0.95) WITHIN GROUP (ORDER BY elapsed_us)
    FILTER (WHERE iter > 0))::numeric, 3) AS warm_p95_us,
  round((MIN(elapsed_us) FILTER (WHERE iter > 0))::numeric, 3) AS warm_min_us,
  round((MAX(elapsed_us) FILTER (WHERE iter > 0))::numeric, 3) AS warm_max_us
FROM pg_typescript_profile_samples
GROUP BY engine
ORDER BY engine;

\echo '=== first 10 calls (microseconds) ==='
SELECT engine, iter, round(elapsed_us::numeric, 3) AS us
FROM pg_typescript_profile_samples
ORDER BY engine, iter;

\echo '=== aggregate stats (microseconds) ==='
SELECT
  engine,
  round(AVG(elapsed_us)::numeric, 3) AS avg_us,
  round(MIN(elapsed_us)::numeric, 3) AS min_us,
  round(MAX(elapsed_us)::numeric, 3) AS max_us,
  round(PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY elapsed_us)::numeric, 3) AS median_us,
  round(PERCENTILE_CONT(0.99) WITHIN GROUP (ORDER BY elapsed_us)::numeric, 3) AS p99_us
FROM pg_typescript_profile_samples
GROUP BY engine
ORDER BY engine;

DROP TABLE pg_typescript_profile_samples;
DROP TABLE profile_project_notes;
DROP TABLE profile_project_members;
DROP TABLE profile_projects;

DROP FUNCTION ts_profile_project_digest(integer);
DROP FUNCTION sql_profile_project_digest(integer);

RESET typescript.max_allow_pg_execute;
