[target.'cfg(target_os="macos")']
# Postgres symbols won't be available until runtime
rustflags = ["-Clink-arg=-Wl,-undefined,dynamic_lookup"]

[target.'cfg(target_os="linux")']
# Use lld to handle V8's local-exec TLS relocations in shared objects
rustflags = ["-Clink-arg=-fuse-ld=lld"]
