-- composite and record type support

CREATE TYPE ts_point AS (x float8, y float8);

-- basic composite return
CREATE OR REPLACE FUNCTION ts_make_point(x float8, y float8) RETURNS ts_point
LANGUAGE typescript AS $$
  return { x, y };
$$;

SELECT (ts_make_point(1.5, 2.5)).*;

-- mixed field types
CREATE TYPE ts_person AS (name text, age int, active bool);

CREATE OR REPLACE FUNCTION ts_make_person(name text, age int) RETURNS ts_person
LANGUAGE typescript AS $$
  return { name, age, active: true };
$$;

SELECT (ts_make_person('Alice', 30)).*;

-- missing fields become NULL
CREATE OR REPLACE FUNCTION ts_partial_point() RETURNS ts_point
LANGUAGE typescript AS $$
  return { x: 42.0 };
$$;

SELECT x, y IS NULL AS y_is_null FROM ts_partial_point();

-- extra JS fields are ignored
CREATE OR REPLACE FUNCTION ts_extra_fields() RETURNS ts_point
LANGUAGE typescript AS $$
  return { x: 1.0, y: 2.0, z: 3.0, label: "ignored" };
$$;

SELECT (ts_extra_fields()).*;

-- null field value
CREATE OR REPLACE FUNCTION ts_null_field() RETURNS ts_person
LANGUAGE typescript AS $$
  return { name: "Bob", age: null, active: false };
$$;

SELECT name, age IS NULL AS age_is_null, active FROM ts_null_field();

-- nested composite type
CREATE TYPE ts_address AS (street text, city text);
CREATE TYPE ts_contact AS (name text, age int, addr ts_address);

CREATE OR REPLACE FUNCTION ts_make_contact() RETURNS ts_contact
LANGUAGE typescript AS $$
  return { name: "Eve", age: 28, addr: { street: "123 Main St", city: "Portland" } };
$$;

SELECT name, age, (addr).street, (addr).city FROM ts_make_contact();

-- many-field composite with jsonb field and array-as-jsonb
CREATE TYPE ts_summary AS (
  id bigint,
  title text,
  body text,
  word_count integer,
  unique_words integer,
  top_word text,
  top_count integer,
  uppercase_count integer,
  tag_hits integer,
  top_words jsonb
);

CREATE OR REPLACE FUNCTION ts_summarize(
  id bigint,
  title text,
  body text,
  tags jsonb
) RETURNS ts_summary
LANGUAGE typescript AS $$
  interface WordInfo {
    word: string;
    count: number;
    is_tag: boolean;
  }

  function normalize(raw: string): string | null {
    const w = raw.toLowerCase().replace(/[^a-z]/g, "");
    return w.length >= 2 ? w : null;
  }

  const tagList: string[] = Array.isArray(tags) ? tags.map(String) : [];
  const raw = (body ?? "").match(/[A-Za-z]+/g) ?? [];
  const uppercaseCount = raw.filter(w => /^[A-Z]+$/.test(w)).length;
  const words = raw.map(normalize).filter((w): w is string => w !== null);

  const counts: Record<string, number> = {};
  for (const w of words) counts[w] = (counts[w] ?? 0) + 1;

  const ranked: WordInfo[] = Object.entries(counts)
    .map(([word, count]) => ({ word, count, is_tag: tagList.includes(word) }))
    .sort((a, b) => b.count - a.count || a.word.localeCompare(b.word));

  const top = ranked[0] ?? null;

  return {
    id,
    title,
    body: words.join(" "),
    word_count: words.length,
    unique_words: Object.keys(counts).length,
    top_word: top?.word ?? null,
    top_count: top?.count ?? 0,
    uppercase_count: uppercaseCount,
    tag_hits: ranked.filter(r => r.is_tag).length,
    top_words: ranked.slice(0, 3),
  };
$$;

SELECT (ts_summarize(
  1, 'Test',
  'HELLO hello world hello World',
  '["hello", "missing"]'::jsonb
)).*;

-- composite with null in nullable field
SELECT top_word IS NOT NULL AS has_top, top_count, tag_hits
FROM ts_summarize(2, 'Empty', '', '[]'::jsonb);

-- trigger calling a typescript function
CREATE TABLE ts_trigger_notes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  body text NOT NULL
);

CREATE TABLE ts_trigger_results (
  note_id bigint PRIMARY KEY REFERENCES ts_trigger_notes(id),
  word_count integer NOT NULL,
  top_word text
);

CREATE TYPE ts_trigger_summary AS (
  note_id bigint,
  word_count integer,
  top_word text
);

CREATE OR REPLACE FUNCTION ts_trigger_summarize(note_id bigint, body text)
RETURNS ts_trigger_summary
LANGUAGE typescript AS $$
  const words = (body ?? "").toLowerCase().match(/[a-z]+/g) ?? [];
  const counts: Record<string, number> = {};
  for (const w of words) counts[w] = (counts[w] ?? 0) + 1;
  const top = Object.entries(counts).sort((a, b) => b[1] - a[1])[0];
  return { note_id, word_count: words.length, top_word: top?.[0] ?? null };
$$;

CREATE OR REPLACE FUNCTION ts_trigger_after_insert()
RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  INSERT INTO ts_trigger_results (note_id, word_count, top_word)
  SELECT (ts_trigger_summarize(NEW.id, NEW.body)).*;
  RETURN NEW;
END;
$$;

CREATE TRIGGER ts_trigger_notes_after_insert
AFTER INSERT ON ts_trigger_notes
FOR EACH ROW
EXECUTE FUNCTION ts_trigger_after_insert();

INSERT INTO ts_trigger_notes (body) VALUES ('apple banana apple cherry apple');

SELECT note_id, word_count, top_word FROM ts_trigger_results;

-- =========================================================================
-- Composite inputs — named types arrive as JS objects
-- =========================================================================

-- named composite input
CREATE OR REPLACE FUNCTION ts_point_magnitude(p ts_point) RETURNS float8
LANGUAGE typescript AS $$
  return Math.sqrt(p.x * p.x + p.y * p.y);
$$;

SELECT ts_point_magnitude(ROW(3.0, 4.0)::ts_point);

-- access fields of a named composite input
CREATE OR REPLACE FUNCTION ts_greet_person(p ts_person) RETURNS text
LANGUAGE typescript AS $$
  return `${p.name} is ${p.age} years old`;
$$;

SELECT ts_greet_person(ROW('Bob', 25, true)::ts_person);

-- null composite input
CREATE OR REPLACE FUNCTION ts_point_or_default(p ts_point) RETURNS float8
LANGUAGE typescript AS $$
  if (p === null) return -1;
  return p.x + p.y;
$$;

SELECT ts_point_or_default(NULL::ts_point);
SELECT ts_point_or_default(ROW(1.0, 2.0)::ts_point);

-- nested composite input
CREATE OR REPLACE FUNCTION ts_contact_city(c ts_contact) RETURNS text
LANGUAGE typescript AS $$
  return c.addr.city;
$$;

SELECT ts_contact_city(ROW('Eve', 28, ROW('123 Main St', 'Portland')::ts_address)::ts_contact);

-- composite input with null fields
CREATE OR REPLACE FUNCTION ts_person_status(p ts_person) RETURNS text
LANGUAGE typescript AS $$
  const age = p.age === null ? "unknown age" : `age ${p.age}`;
  const status = p.active ? "active" : "inactive";
  return `${p.name}: ${age}, ${status}`;
$$;

SELECT ts_person_status(ROW('Alice', NULL, false)::ts_person);

-- multiple composite inputs
CREATE OR REPLACE FUNCTION ts_point_distance(a ts_point, b ts_point) RETURNS float8
LANGUAGE typescript AS $$
  const dx = a.x - b.x;
  const dy = a.y - b.y;
  return Math.sqrt(dx * dx + dy * dy);
$$;

SELECT ts_point_distance(ROW(0.0, 0.0)::ts_point, ROW(3.0, 4.0)::ts_point);

-- composite input and composite output
CREATE OR REPLACE FUNCTION ts_scale_point(p ts_point, factor float8) RETURNS ts_point
LANGUAGE typescript AS $$
  return { x: p.x * factor, y: p.y * factor };
$$;

SELECT (ts_scale_point(ROW(3.0, 4.0)::ts_point, 2.0)).*;

-- =========================================================================
-- RETURNS RECORD — anonymous composite via OUT params or caller AS clause
-- =========================================================================

-- OUT parameters
CREATE OR REPLACE FUNCTION ts_record_out(
  IN x int, OUT a int, OUT b text
) RETURNS RECORD
LANGUAGE typescript AS $$
  return { a: x * 2, b: "hello" };
$$;

SELECT * FROM ts_record_out(21);

-- caller-side AS clause
CREATE OR REPLACE FUNCTION ts_record_anon(x int) RETURNS RECORD
LANGUAGE typescript AS $$
  return { name: "Alice", age: x };
$$;

SELECT * FROM ts_record_anon(30) AS (name text, age int);

-- NULL return from RECORD function
CREATE OR REPLACE FUNCTION ts_record_null() RETURNS RECORD
LANGUAGE typescript AS $$
  return null;
$$;

SELECT * FROM ts_record_null() AS (a int, b text);

-- missing fields become NULL
CREATE OR REPLACE FUNCTION ts_record_partial(x int)
  RETURNS RECORD
LANGUAGE typescript AS $$
  return { a: x };
$$;

SELECT * FROM ts_record_partial(42) AS (a int, b text, c bool);

-- multiple OUT parameters with mixed types
CREATE OR REPLACE FUNCTION ts_record_multi_out(
  IN val float8,
  OUT doubled float8,
  OUT label text,
  OUT flag bool
) RETURNS RECORD
LANGUAGE typescript AS $$
  return { doubled: val * 2, label: "result", flag: val > 0 };
$$;

SELECT * FROM ts_record_multi_out(3.14);

-- anonymous RECORD input (columns are named f1, f2, … by default)
CREATE OR REPLACE FUNCTION ts_record_sum(r record) RETURNS int
LANGUAGE typescript AS $$
  return r.f1 + r.f2;
$$;

SELECT ts_record_sum(ROW(10, 32));
