-- composite type returns from TypeScript functions

CREATE TYPE ts_point AS (x float8, y float8);

-- basic composite return
CREATE OR REPLACE FUNCTION ts_make_point(x float8, y float8) RETURNS ts_point
LANGUAGE typescript AS $$
  return { x, y };
$$;

SELECT (ts_make_point(1.5, 2.5)).*;

-- mixed field types
CREATE TYPE ts_person AS (name text, age int, active bool);

CREATE OR REPLACE FUNCTION ts_make_person(name text, age int) RETURNS ts_person
LANGUAGE typescript AS $$
  return { name, age, active: true };
$$;

SELECT (ts_make_person('Alice', 30)).*;

-- missing fields become NULL
CREATE OR REPLACE FUNCTION ts_partial_point() RETURNS ts_point
LANGUAGE typescript AS $$
  return { x: 42.0 };
$$;

SELECT x, y IS NULL AS y_is_null FROM ts_partial_point();

-- extra JS fields are ignored
CREATE OR REPLACE FUNCTION ts_extra_fields() RETURNS ts_point
LANGUAGE typescript AS $$
  return { x: 1.0, y: 2.0, z: 3.0, label: "ignored" };
$$;

SELECT (ts_extra_fields()).*;

-- null field value
CREATE OR REPLACE FUNCTION ts_null_field() RETURNS ts_person
LANGUAGE typescript AS $$
  return { name: "Bob", age: null, active: false };
$$;

SELECT name, age IS NULL AS age_is_null, active FROM ts_null_field();

-- nested composite type
CREATE TYPE ts_address AS (street text, city text);
CREATE TYPE ts_contact AS (name text, age int, addr ts_address);

CREATE OR REPLACE FUNCTION ts_make_contact() RETURNS ts_contact
LANGUAGE typescript AS $$
  return { name: "Eve", age: 28, addr: { street: "123 Main St", city: "Portland" } };
$$;

SELECT name, age, (addr).street, (addr).city FROM ts_make_contact();

-- many-field composite with jsonb field and array-as-jsonb
CREATE TYPE ts_summary AS (
  id bigint,
  title text,
  body text,
  word_count integer,
  unique_words integer,
  top_word text,
  top_count integer,
  uppercase_count integer,
  tag_hits integer,
  top_words jsonb
);

CREATE OR REPLACE FUNCTION ts_summarize(
  id bigint,
  title text,
  body text,
  tags jsonb
) RETURNS ts_summary
LANGUAGE typescript AS $$
  interface WordInfo {
    word: string;
    count: number;
    is_tag: boolean;
  }

  function normalize(raw: string): string | null {
    const w = raw.toLowerCase().replace(/[^a-z]/g, "");
    return w.length >= 2 ? w : null;
  }

  const tagList: string[] = Array.isArray(tags) ? tags.map(String) : [];
  const raw = (body ?? "").match(/[A-Za-z]+/g) ?? [];
  const uppercaseCount = raw.filter(w => /^[A-Z]+$/.test(w)).length;
  const words = raw.map(normalize).filter((w): w is string => w !== null);

  const counts: Record<string, number> = {};
  for (const w of words) counts[w] = (counts[w] ?? 0) + 1;

  const ranked: WordInfo[] = Object.entries(counts)
    .map(([word, count]) => ({ word, count, is_tag: tagList.includes(word) }))
    .sort((a, b) => b.count - a.count || a.word.localeCompare(b.word));

  const top = ranked[0] ?? null;

  return {
    id,
    title,
    body: words.join(" "),
    word_count: words.length,
    unique_words: Object.keys(counts).length,
    top_word: top?.word ?? null,
    top_count: top?.count ?? 0,
    uppercase_count: uppercaseCount,
    tag_hits: ranked.filter(r => r.is_tag).length,
    top_words: ranked.slice(0, 3),
  };
$$;

SELECT (ts_summarize(
  1, 'Test',
  'HELLO hello world hello World',
  '["hello", "missing"]'::jsonb
)).*;

-- composite with null in nullable field
SELECT top_word IS NOT NULL AS has_top, top_count, tag_hits
FROM ts_summarize(2, 'Empty', '', '[]'::jsonb);

-- trigger calling a typescript function
CREATE TABLE ts_trigger_notes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  body text NOT NULL
);

CREATE TABLE ts_trigger_results (
  note_id bigint PRIMARY KEY REFERENCES ts_trigger_notes(id),
  word_count integer NOT NULL,
  top_word text
);

CREATE TYPE ts_trigger_summary AS (
  note_id bigint,
  word_count integer,
  top_word text
);

CREATE OR REPLACE FUNCTION ts_trigger_summarize(note_id bigint, body text)
RETURNS ts_trigger_summary
LANGUAGE typescript AS $$
  const words = (body ?? "").toLowerCase().match(/[a-z]+/g) ?? [];
  const counts: Record<string, number> = {};
  for (const w of words) counts[w] = (counts[w] ?? 0) + 1;
  const top = Object.entries(counts).sort((a, b) => b[1] - a[1])[0];
  return { note_id, word_count: words.length, top_word: top?.[0] ?? null };
$$;

CREATE OR REPLACE FUNCTION ts_trigger_after_insert()
RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  INSERT INTO ts_trigger_results (note_id, word_count, top_word)
  SELECT (ts_trigger_summarize(NEW.id, NEW.body)).*;
  RETURN NEW;
END;
$$;

CREATE TRIGGER ts_trigger_notes_after_insert
AFTER INSERT ON ts_trigger_notes
FOR EACH ROW
EXECUTE FUNCTION ts_trigger_after_insert();

INSERT INTO ts_trigger_notes (body) VALUES ('apple banana apple cherry apple');

SELECT note_id, word_count, top_word FROM ts_trigger_results;
