CREATE TABLE ts_pg_execute_people (
  id int PRIMARY KEY,
  name text NOT NULL,
  meta jsonb NOT NULL
);

INSERT INTO ts_pg_execute_people (id, name, meta) VALUES
  (1, 'Ada', '{"role":"admin","active":true}'),
  (2, 'Grace', '{"role":"author","active":false}');

CREATE TABLE ts_pg_execute_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  message text NOT NULL
);

CREATE OR REPLACE FUNCTION ts_pg_execute_select(user_id int) RETURNS bool
LANGUAGE typescript AS $$
  const result = _pg.execute(
    "SELECT id, name, meta FROM ts_pg_execute_people WHERE id = $1",
    user_id,
  );
  const row = result.rows[0];
  const checks = {
    command_ok: result.command === "SELECT",
    row_count_ok: result.rowCount === 1,
    name_ok: row.name === "Ada",
    json_ok: row.meta !== null && row.meta.role === "admin",
  };
  return Object.values(checks).every((value) => value === true);
$$;

SELECT ts_pg_execute_select(1) AS select_smoke_ok;

CREATE OR REPLACE FUNCTION ts_pg_execute_numeric_results() RETURNS bool
LANGUAGE typescript AS $$
  const result = _pg.execute(
    `
      SELECT
        $1::int2 AS smallint_value,
        $2::int4 AS integer_value,
        $3::int8 AS bigint_value,
        $4::float4 AS real_value,
        $5::float8 AS double_value
    `,
    7,
    42,
    900719925474099,
    1.25,
    3.5,
  );
  const row = result.rows[0];
  const checks = {
    command_ok: result.command === "SELECT",
    row_count_ok: result.rowCount === 1,
    smallint_ok: row.smallint_value === 7,
    integer_ok: row.integer_value === 42,
    bigint_ok: row.bigint_value === 900719925474099,
    real_ok: Math.abs(row.real_value - 1.25) < 0.0001,
    double_ok: row.double_value === 3.5,
  };
  return Object.values(checks).every((value) => value === true);
$$;

SELECT ts_pg_execute_numeric_results() AS numeric_results_ok;

CREATE OR REPLACE FUNCTION ts_pg_execute_scalar_results() RETURNS bool
LANGUAGE typescript AS $$
  const result = _pg.execute(
    `
      SELECT
        $1::bool AS bool_value,
        $2::text AS text_value,
        $3::varchar AS varchar_value
    `,
    true,
    "hello",
    "world",
  );
  const row = result.rows[0];
  const checks = {
    command_ok: result.command === "SELECT",
    row_count_ok: result.rowCount === 1,
    bool_ok: row.bool_value === true,
    text_ok: row.text_value === "hello",
    varchar_ok: row.varchar_value === "world",
  };
  return Object.values(checks).every((value) => value === true);
$$;

SELECT ts_pg_execute_scalar_results() AS scalar_results_ok;

CREATE OR REPLACE FUNCTION ts_pg_execute_json_result() RETURNS bool
LANGUAGE typescript AS $$
  const result = _pg.execute(
    "SELECT $1::jsonb AS json_value",
    { role: "admin", count: 2 },
  );
  const row = result.rows[0];
  const checks = {
    command_ok: result.command === "SELECT",
    row_count_ok: result.rowCount === 1,
    json_type_ok: typeof row.json_value === "object",
    json_not_null_ok: row.json_value !== null,
    json_role_ok: row.json_value.role === "admin",
    json_count_ok: row.json_value.count === 2,
  };
  return Object.values(checks).every((value) => value === true);
$$;

SELECT ts_pg_execute_json_result() AS json_result_ok;

CREATE OR REPLACE FUNCTION ts_pg_execute_uuid_result(uuid_text text) RETURNS bool
LANGUAGE typescript AS $$
  const result = _pg.execute(
    "SELECT $1::uuid AS uuid_value",
    { type: "uuid", value: uuid_text },
  );
  const checks = {
    command_ok: result.command === "SELECT",
    row_count_ok: result.rowCount === 1,
    uuid_ok: result.rows[0].uuid_value === uuid_text,
  };
  return Object.values(checks).every((value) => value === true);
$$;

SELECT ts_pg_execute_uuid_result('550e8400-e29b-41d4-a716-446655440000') AS uuid_result_ok;

CREATE OR REPLACE FUNCTION ts_pg_execute_numeric_result() RETURNS bool
LANGUAGE typescript AS $$
  const result = _pg.execute(
    "SELECT $1::numeric AS numeric_value",
    { type: "numeric", value: "12345.6789" },
  );
  const checks = {
    command_ok: result.command === "SELECT",
    row_count_ok: result.rowCount === 1,
    numeric_ok: result.rows[0].numeric_value === "12345.6789",
  };
  return Object.values(checks).every((value) => value === true);
$$;

SELECT ts_pg_execute_numeric_result() AS numeric_result_ok;

CREATE OR REPLACE FUNCTION ts_pg_execute_result_nulls() RETURNS bool
LANGUAGE typescript AS $$
  const result = _pg.execute(
    "SELECT NULL::text AS nullable_text, NULL::jsonb AS nullable_json, $1::int4 AS present_value",
    9,
  );
  const row = result.rows[0];
  const checks = {
    command_ok: result.command === "SELECT",
    row_count_ok: result.rowCount === 1,
    nullable_text_ok: row.nullable_text === null,
    nullable_json_ok: row.nullable_json === null,
    present_value_ok: row.present_value === 9,
  };
  return Object.values(checks).every((value) => value === true);
$$;

SELECT ts_pg_execute_result_nulls() AS result_nulls_ok;

CREATE OR REPLACE FUNCTION ts_pg_execute_json_param() RETURNS bool
LANGUAGE typescript AS $$
  const result = _pg.execute(
    "SELECT (($1->>'count')::int + 1) AS total",
    { count: 41 },
  );
  const checks = {
    command_ok: result.command === "SELECT",
    row_count_ok: result.rowCount === 1,
    total_ok: result.rows[0].total === 42,
  };
  return Object.values(checks).every((value) => value === true);
$$;

SELECT ts_pg_execute_json_param() AS inferred_json_param_ok;

CREATE OR REPLACE FUNCTION ts_pg_execute_typed(uuid_text text) RETURNS bool
LANGUAGE typescript AS $$
  const result = _pg.execute(
    "SELECT $1::uuid::text AS value",
    { type: "uuid", value: uuid_text },
  );
  const checks = {
    command_ok: result.command === "SELECT",
    row_count_ok: result.rowCount === 1,
    value_ok: result.rows[0].value === uuid_text,
  };
  return Object.values(checks).every((value) => value === true);
$$;

SELECT ts_pg_execute_typed('550e8400-e29b-41d4-a716-446655440000') AS typed_param_ok;

CREATE OR REPLACE FUNCTION ts_pg_execute_invalid_type_ref() RETURNS bool
LANGUAGE typescript AS $$
  try {
    _pg.execute(
      "SELECT $1::int4 AS value",
      { type: 23, value: 1 },
    );
    return false;
  } catch (err) {
    return String(err.message ?? err) ===
      "_pg.execute typed parameters require a string type name";
  }
$$;

SELECT ts_pg_execute_invalid_type_ref() AS numeric_type_ref_rejected_ok;

CREATE OR REPLACE FUNCTION ts_pg_execute_insert_checks() RETURNS bool
LANGUAGE typescript AS $$
  const first = _pg.execute(
    "INSERT INTO ts_pg_execute_logs (message) VALUES ($1)",
    "hello",
  );
  const second = _pg.execute(
    "INSERT INTO ts_pg_execute_logs (message) VALUES ($1)",
    "world",
  );
  const third = _pg.execute(
    "INSERT INTO ts_pg_execute_logs (message) VALUES ($1)",
    "again",
  );
  const count = _pg.execute("SELECT count(*) AS total FROM ts_pg_execute_logs");
  const checks = {
    first_command_ok: first.command === "INSERT",
    first_row_count_ok: first.rowCount === 1,
    second_command_ok: second.command === "INSERT",
    second_row_count_ok: second.rowCount === 1,
    third_rows_empty_ok: Array.isArray(third.rows) && third.rows.length === 0,
    inserted_rows_ok: count.rows[0].total === 3,
  };
  return Object.values(checks).every((value) => value === true);
$$;

SELECT ts_pg_execute_insert_checks() AS insert_checks_ok;
