LOAD 'pg_typescript';

CREATE EXTENSION IF NOT EXISTS pg_typescript;

DO $$
BEGIN
  EXECUTE format(
    'ALTER DATABASE %I SET typescript.max_allow_import = %L',
    current_database(),
    'esm.sh'
  );
END;
$$;

DROP TABLE IF EXISTS public.stream_note_summaries;
DROP TABLE IF EXISTS public.stream_notes;

CREATE TABLE public.stream_notes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  author text NOT NULL,
  body text NOT NULL,
  tags jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.stream_note_summaries (
  note_id bigint PRIMARY KEY REFERENCES public.stream_notes(id) ON DELETE CASCADE,
  author text NOT NULL,
  normalized_body text NOT NULL,
  total_tokens integer NOT NULL,
  unique_tokens integer NOT NULL,
  dominant_token text,
  dominant_count integer NOT NULL,
  uppercase_token_count integer NOT NULL,
  tag_match_count integer NOT NULL,
  top_tokens jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CHECK (dominant_count >= 0),
  CHECK (total_tokens >= 0),
  CHECK (unique_tokens >= 0),
  CHECK (uppercase_token_count >= 0),
  CHECK (tag_match_count >= 0)
);

CREATE TYPE public.stream_note_summary AS (
  note_id bigint,
  author text,
  normalized_body text,
  total_tokens integer,
  unique_tokens integer,
  dominant_token text,
  dominant_count integer,
  uppercase_token_count integer,
  tag_match_count integer,
  top_tokens jsonb
);

CREATE OR REPLACE FUNCTION public.ts_project_note_summary(
  note_id bigint,
  author text,
  body text,
  tags jsonb
) RETURNS public.stream_note_summary
LANGUAGE typescript
SET typescript.allow_import = 'esm.sh'
SET typescript.import_map = '{"imports":{"lodash":"https://esm.sh/lodash@4.17.23"}}'
AS $$
  interface TopToken {
    token: string;
    occurrences: number;
    matches_tag: boolean;
  }

  interface NoteSummary {
    note_id: number;
    author: string;
    normalized_body: string;
    total_tokens: number;
    unique_tokens: number;
    dominant_token: string | null;
    dominant_count: number;
    uppercase_token_count: number;
    tag_match_count: number;
    top_tokens: TopToken[];
  }

  // Normalize tokens just enough to make the uppercase demo visible without
  // hiding the original word too aggressively.
  function normalizeToken(rawToken: string): string | null {
    const token = lodash.trim(lodash.toLower(rawToken), "'");

    if (token.length < 2 || /^[0-9]+$/.test(token)) {
      return null;
    }

    return token;
  }

  // Tags get normalized separately so the summary can report whether the most
  // important words in the note line up with the note metadata.
  const normalizedTags = lodash
    .chain(Array.isArray(tags) ? tags : [])
    .map((tag) =>
      lodash
        .toLower(String(tag))
        .replace(/[^a-z0-9]+/g, "-")
        .replace(/^-+|-+$/g, ""),
    )
    .filter((tag) => tag.length > 0)
    .uniq()
    .take(4)
    .value();

  // Preserve the original token casing so the summary can count how many words
  // arrived uppercase, then build a normalized token stream for aggregation.
  const rawTokens = lodash.words(lodash.defaultTo(body, ""), /[A-Za-z0-9']+/g);
  const tokens = lodash
    .chain(rawTokens)
    .map(normalizeToken)
    .compact()
    .value() as string[];
  const counts = lodash.countBy(tokens);

  // Rank every unique token once, then keep a small top-N list for storage.
  const rankedTokens = lodash
    .chain(lodash.toPairs(counts))
    .map(([token, occurrences]) => ({
      token,
      occurrences,
      matches_tag: normalizedTags.some(
        (tag) => lodash.includes(tag, token) || lodash.includes(token, tag),
      ),
    }))
    .orderBy(["occurrences", "token"], ["desc", "asc"])
    .value() as TopToken[];
  const topTokens = rankedTokens.slice(0, 5);
  const dominantToken = rankedTokens[0] ?? null;
  const uppercaseTokenCount = rawTokens.filter(
    (token) => /[A-Z]/.test(token) && token === token.toUpperCase(),
  ).length;

  // Return one composite row summarizing the note so the trigger can insert it
  // directly into the derived table.
  const summary: NoteSummary = {
    note_id,
    author,
    normalized_body: tokens.join(" "),
    total_tokens: tokens.length,
    unique_tokens: Object.keys(counts).length,
    dominant_token: dominantToken?.token ?? null,
    dominant_count: dominantToken?.occurrences ?? 0,
    uppercase_token_count: uppercaseTokenCount,
    tag_match_count: rankedTokens.filter((token) => token.matches_tag).length,
    top_tokens: topTokens,
  };

  return summary;
$$;

CREATE OR REPLACE FUNCTION public.stream_note_summary_after_insert()
RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  INSERT INTO public.stream_note_summaries (
    note_id,
    author,
    normalized_body,
    total_tokens,
    unique_tokens,
    dominant_token,
    dominant_count,
    uppercase_token_count,
    tag_match_count,
    top_tokens
  )
  SELECT (public.ts_project_note_summary(NEW.id, NEW.author, NEW.body, NEW.tags)).*;

  RETURN NEW;
END;
$$;

CREATE TRIGGER stream_note_summary_after_insert
AFTER INSERT ON public.stream_notes
FOR EACH ROW
EXECUTE FUNCTION public.stream_note_summary_after_insert();
